### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by SwetSampadSahu** [istvanmakary/react-debugger-server#1] opened 2018-10-09 10:33 UTC
Hi,

Whenever I try to start the server with npm install, am getting the following error : 

```
npm start

> debug-server@1.0.0 start /home/user/Documents/react-debugger-server-master
> node ./dist/index.js

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Function.listen (/home/user/Documents/react-debugger-server-master/node_modules/express/lib/application.js:618:24)
    at Server.setupServer (/home/user/Documents/react-debugger-server-master/dist/index.js:153:31)
    at Server.<anonymous> (/home/user/Documents/react-debugger-server-master/dist/index.js:118:22)
    at step (/home/user/Documents/react-debugger-server-master/dist/index.js:39:23)
    at Object.next (/home/user/Documents/react-debugger-server-master/dist/index.js:20:53)
    at /home/user/Documents/react-debugger-server-master/dist/index.js:14:71
    at new Promise (<anonymous>)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! debug-server@1.0.0 start: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the debug-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-10-09T10_22_13_604Z-debug.log
```

-------------------------------------------------------------------------------------------------------------------------------------------

Also the following is the '2018-10-09T10_22_13_604Z-debug.log' content : 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle debug-server@1.0.0~prestart: debug-server@1.0.0
6 info lifecycle debug-server@1.0.0~start: debug-server@1.0.0
7 verbose lifecycle debug-server@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle debug-server@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Documents/react-debugger-server-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle debug-server@1.0.0~start: CWD: /home/user/Documents/react-debugger-server-master
10 silly lifecycle debug-server@1.0.0~start: Args: [ '-c', 'node ./dist/index.js' ]
11 silly lifecycle debug-server@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle debug-server@1.0.0~start: Failed to exec start script
13 verbose stack Error: debug-server@1.0.0 start: `node ./dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid debug-server@1.0.0
15 verbose cwd /home/user/Documents/react-debugger-server-master
16 verbose Linux 4.4.0-79-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.10.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error debug-server@1.0.0 start: `node ./dist/index.js`
22 error Exit status 1
23 error Failed at the debug-server@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

My Node version is 10.10.0
and NPM ersion is 6.4.1

Is there anything am missing? Can someone help me with this?

**Comment by istvanmakary** [comment] 2018-10-09 10:55
Hey!

Thanks for using react native debugger :)

The problem you are facing is caused by the config.json file in the project root.

The config should look like this in your case:
```
{
  "url": "http://localhost:3030/",
  "limit": 100,
  "port": 3030,
  "user": "admin",
  "password": "Secret123"
}
```
I hope it solves the issue!

Keep me updated

**Comment by SwetSampadSahu** [comment] 2018-10-09 11:00
> Hey!
> 
> Thanks for using react native debugger :)
> 
> The problem you are facing is caused by the config.json file in the project root.
> 
> The config should look like this in your case:
> 
> ```
> {
>   "url": "http://localhost:3030/",
>   "limit": 100,
>   "port": 3030,
>   "user": "admin",
>   "password": "Secret123"
> }
> ```
> I hope it solves the issue!
> 
> Keep me updated

Yes. This helped. Thanks a lot! :+1:

**Comment by istvanmakary** [comment] 2018-10-09 12:44
Glad to hear,
I'll close this issue then.

**Closed as completed by istvanmakary** 2018-10-09 12:44 UTC
